### PR TITLE
Feature/cmp 988/i18n and l10n service & structure

### PR DESCRIPTION
**Pull request by davidzynda**
# Why we create this PR?
 We need a translation service to have at least two languages DE and EN

## PR Linked to:
https://jira.catena-x.net/browse/CMP-988

### CODE REVIEW

**Comment by matbmoser** [comment]
I opened an IP issue for the libraries here now we need to wait: 

- [ ] [npm/npmjs/@intlify/core-base/9.4.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12452) 
- [ ] [npm/npmjs/@intlify/message-compiler/9.4.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12451)
- [ ] [npm/npmjs/@intlify/shared/9.4.1](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12450)

**Comment by matbmoser** [comment]
i updated the version of the library to v9.2.2 and there is no dependecies not approved

**Comment by matbmoser** [comment]
Also fixed an axios vulnerability here

**Comment by matbmoser** [comment]
image
Works fine !

**Comment by matbmoser** [comment]
image
With the DPP it shows like this

**Comment by matbmoser** [comment]
With the Battery it works:
image

**Comment by matbmoser** [comment]
image
The translation also works in the battery correctly

**Review by matbmoser — CHANGES_REQUESTED** [review]
https://github.com/catenax-ng/tx-digital-product-pass/pull/199#issuecomment-1875050572

Solve this issue with the DPP and merge develop into your branch to resolve the conflicts and I can approve it  :)

**Review by saudkhan116 — CHANGES_REQUESTED** [review]
Please resolve the conflicts

**Review by saudkhan116 — APPROVED** [review]

**Pull request merged**
