### PR TITLE
Feature/cmp 1076/units update

### PR DESCRIPTION
**Pull request by davidzynda**
# Why we create this PR?
 
We are missing some data, hardcoded units, and translations
 
# What we want to achieve with this PR?
 
Fill out the missing things
 
# What is new?
 

## PR Linked to:

<< If there is a ticket include it here >>

| Tickets |
| :---:   |

| [cmp-1076](https://jira.catena-x.net/browse/CMP-1076)  |

### CODE REVIEW

**Review by matbmoser — APPROVED** [review]
I can not check if everything that was missing was fixed. However I think its fine for me .

**Comment by matbmoser** [comment]
@dsrparracho can you do this review for me? I think everything is fine but I would like a second opinion.

**Review by matbmoser — CHANGES_REQUESTED** [review]
Still some points missing @dsrparracho  will review

**Comment by dsrparracho** [comment]
@davidzynda I'm still need to review two passports that I'm not being able to retrieve it yet.

For the ones that I could review, these are my notes:
CX:MFG024:PRT-30001:
- Should null fields be updated to like "NA" (Not Applied) or "--"? Like in Metadata the field Predecessor.
- On Handling tab the field Exemption has some description (as I could see from the data that comes from backend) but in the UI appears as "--".
CX:MAT7814:NCM-6789
- On Handling Tab, concentration unit of "kilogram" isn't shown.
- On Sustainability Tab, the mass percentage values from Nickel and Cobalt shouldn't be shown? (question)

**Comment by dsrparracho** [comment]
For the rest of the examples there is my final comments on this PR: 
CX:4566377388:NO-498194819574934690486419
- On General Information Tab, couldn't the Product Description box be naturally
widder, so that the description be more readble. 
Like the dimensions box. Because if I shrink the window, it gets less readable, even if just a little bit

CX:M4GP456:IMR18650V1
- On Performance Tab there is a "Model" information with power capability value, I believe it should be "Power Capability" instead of Model.
- On Electrochemical Properties tab the values of Resistance aren't being displayed. 
Shouldn't the values of energyRoundtripEfficiencyChange and energyRoundtripEfficiency also be displayed? (question)

**Review by matbmoser — APPROVED** [review]

**Pull request merged**
