### PR TITLE
passport view refactor

### PR DESCRIPTION
**Pull request by davidzynda**
## What this PR changes/adds

PassportView refactors necessary to keep the code DRY and futureproof.

### CODE REVIEW

**Review by saudkhan116 — APPROVED** [review]

**Comment by matbmoser** [comment]
image
The negotiation works

**Review by matbmoser — CHANGES_REQUESTED** [review]
Check why it is not printing passport

**Comment by davidzynda** [comment]
> Check why it is not printing passport

Two mistakes in BatteryComposition component blocked it. Now fixed.

**Comment by matbmoser** [comment]
image
I am not able to visualize the history table. It tells me that the authentification failed...

**Comment by matbmoser** [comment]
image
This happens in the actual version when we log in with CX Admin

**Comment by matbmoser** [comment]
image
As we know the daps is not working so I can not test the actual functionality,
However I will trust that the bug was resolved and approve this

Thank you very much @davidzynda 💯

**Comment by davidzynda** [comment]
I don't think we should use CX admin, but it makes sense to at least check why it's happening

**Review by matbmoser — APPROVED** [review]

**Comment by davidzynda** [comment]
> image As we know the daps is not working so I can not test the actual functionality, However I will trust that the bug was resolved and approve this
> 
> Thank you very much @davidzynda 💯

@matbmoser Thank you for your thorough review and for the trust you have placed in me. I will not fail you!

**Comment by matbmoser** [comment]
This ticket was created to track the bug [https://jira.catena-x.net/browse/CMP-532](https://jira.catena-x.net/browse/CMP-532)

**Pull request merged**
